name: ResourcedetailsAPIStaging
on: [push]
env: 
  NAMESPACE: projectbose

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrprojectbose.azurecr.io
        username: ${{ secrets.acr_acrprojectbose_username }}
        password: ${{ secrets.acr_acrprojectbose_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/api/API/ResourcedetailsAPI" -f  "api/API/ResourcedetailsAPI/Dockerfile" -t acrprojectbose.azurecr.io/projectboseaks:${{ github.sha }}-resourcedetails --label dockerfile-path=api/API/ResourcedetailsAPI/Dockerfile
        docker push acrprojectbose.azurecr.io/projectboseaks:${{ github.sha }}-resourcedetails
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_projectboseaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ${{ env.NAMESPACE  }} | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ${{ env.NAMESPACE  }}`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: acrprojectbose.azurecr.io
        container-registry-username: ${{ secrets.acr_acrprojectbose_username }}
        container-registry-password: ${{ secrets.acr_acrprojectbose_password }}
        secret-name: projectboseadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          manifests/deployResourcedetailsAPI.yml
          manifests/serviceResourcedetailsAPI.yml
        images: |
          acrprojectbose.azurecr.io/projectboseaks:${{ github.sha }}-resourcedetails
        imagepullsecrets: |
          projectboseadockerauth
